name: clean_architecture_poke_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  bloc: ^9.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  geolocator: ^14.0.1
  get_it: ^8.0.3
  go_router: ^16.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  random_name_generator: ^1.1.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
